### ISSUE TITLE
如何从test.py输出的results.mat中复原测试的图片？

### ISSUE THREAD

**Issue by Lie65** [Junchao2018/Polarization-image-fusion#3]
作者您好，我最近在使用您的程序的时候遇到了点小问题——请问您是怎么跑测试的呢？
测试图像也是像训练图像一样切成多个patches吗？如果是，又要如何从test.py输出的results.mat中复原测试的图片呢，请问作者有这样的程序吗？

**Comment by 1844280369** [comment]
你好，请问你解决了吗？

**Comment by Junchao2018** [comment]
测试图像不用切成小块，直接整幅图像进行测试即可，参照GenerateTrainingPatches_Tensorflow.m这个程序生成测试用的数据，里面不需要做剪切成小块的操作。

**Comment by Lie65** [comment]
> 测试图像不用切成小块，直接整幅图像进行测试即可，参照GenerateTrainingPatches_Tensorflow.m这个程序生成测试用的数据，里面不需要做剪切成小块的操作。
非常感谢

**Comment by Lie65** [comment]
@Junchao2018 
已解决，非常感谢

**Comment by 1844280369** [comment]
@Lie65 你好，请问是如何解决的呢？能稍微说一下，我再尝试改GenerateTrainingPatches_Tensorflow.m，但是总是无法进行测试。

**Comment by Lie65** [comment]
@1844280369 
你在GenerateTrainingPatches_Tensorflow.m把patch size设置成你原图的大小，然后生成.mat文件进行测试就行了

**Comment by 1844280369** [comment]
@Lie65 好的，十分感谢！

**Comment by Bucai-meng** [comment]
> @1844280369 你在GenerateTrainingPatches_Tensorflow.m把patch size设置成你原图的大小，然后生成.mat文件进行测试就行了
请问

> @1844280369 你在GenerateTrainingPatches_Tensorflow.m把patch size设置成你原图的大小，然后生成.mat文件进行测试就行了

你好 请问如果图像不是m*m的大小，而是m*n，最终融合后的一整张图像被分了好几个块（相当于窗口滑动）怎么解决呢

**Comment by Lie65** [comment]
> > @1844280369 你在GenerateTrainingPatches_Tensorflow.m把patch size设置成你原图的大小，然后生成.mat文件进行测试就行了
> > 请问
> 
> > @1844280369 你在GenerateTrainingPatches_Tensorflow.m把patch size设置成你原图的大小，然后生成.mat文件进行测试就行了
> 
> 你好 请问如果图像不是m_m的大小，而是m_n，最终融合后的一整张图像被分了好几个块（相当于窗口滑动）怎么解决呢

这个问题我也没遇到过呢，不好意思了

**Comment by 1844280369** [comment]
> 你好 请问如果图像不是_mm的大小，而是mn_，最终融合后的一整张图像被分了好几个块（相当于窗口滑动）怎么解决呢

我是在运行前加了一步把图片裁剪为指定尺寸的步骤，然后改backword.py里切片尺寸、test.py改为剪裁的尺寸。。。然后是正常运行的，并没有出现你说的那个问题.
